updates:
- commit-message:
    prefix: chore(deps)
  directory: /
  groups:
    dev-dependencies:
      dependency-type: development
  labels:
  - dependencies
  open-pull-requests-limit: 5
  package-ecosystem: npm
  schedule:
    day: monday
    interval: weekly
    time: 09:00
    timezone: Europe/Paris
- commit-message:
    prefix: chore(pre-commit)
  directory: /
  labels:
  - dependencies
  open-pull-requests-limit: 5
  package-ecosystem: pre-commit
  schedule:
    day: monday
    interval: weekly
    time: 09:00
    timezone: Europe/Paris
- commit-message:
    prefix: chore(ci)
  directory: /
  labels:
  - dependencies
  - ci
  open-pull-requests-limit: 5
  package-ecosystem: github-actions
  schedule:
    day: monday
    interval: weekly
    time: 09:00
    timezone: Europe/Paris
version: 2
