sonar.projectKey=chrysa_satisfactory-automated_calculator
sonar.organization=chrysa
sonar.projectName=satisfactory-automated_calculator
sonar.sources=src,backend
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/.mypy_cache/**,**/backups/**,**/dist/**
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
